spring:
  application:
    name: order-management
  datasource:
    url: jdbc:postgresql://localhost:5433/enterprise_orders
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
